name: home_assets3
description: Home's Inventory, Simplified
publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.7.2
  firebase_ui_auth: ^1.8.0
  firebase_ui_oauth_apple: ^1.2.11
  firebase_ui_oauth_google: ^1.2.11
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  flutter_riverpod: ^2.4.0
  firebase_auth: ^4.10.0
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  image_picker: ^1.0.4
  firebase_storage: ^11.2.7
  uuid: ^4.1.0
  loader_overlay: ^2.3.2
  jiffy: ^6.2.1
  photo_view: ^0.14.0
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/welcome_background.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  web:
    generate: true
