// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfuln8ImqQp6SwQzIKCudJtnyQUUAHCvU',
    appId: '1:454120191953:web:b7a3c21f1649c563d292f0',
    messagingSenderId: '454120191953',
    projectId: 'home-assets-3',
    authDomain: 'home-assets-3.firebaseapp.com',
    storageBucket: 'home-assets-3.appspot.com',
    measurementId: 'G-6GBFWNK3T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5RKNFfGSRt3M_fgKB36ZToF92pY6qHYE',
    appId: '1:454120191953:android:9b4fb6e7c8f1c224d292f0',
    messagingSenderId: '454120191953',
    projectId: 'home-assets-3',
    storageBucket: 'home-assets-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzYtJ1mppZa_6F4OkMMZvhBmhABvT-vsY',
    appId: '1:454120191953:ios:6e4a5e68b5f18397d292f0',
    messagingSenderId: '454120191953',
    projectId: 'home-assets-3',
    storageBucket: 'home-assets-3.appspot.com',
    iosClientId: '454120191953-2mt5fcksbtpuh4u9g6qkr3ib7kclrkdi.apps.googleusercontent.com',
    iosBundleId: 'com.dot4soft.homeAssets3',
  );
}
